# Álgebra lineal y Julia #


## Vectores ##

### Vector columna ###

Para crear un vector columna con entradas 1,2 y 3 utilizamos la orden `[1,2,3]`.

### Vector fila ###

Para crear un vector fila con entradas 1,2 y 3 utilizamos la orden `[1 2 3]`.

#### Pregunta ####

¿Cuál es el tipo de cada uno de los vectores anteriores? ¿En qué se diferencia
la salida de `typeof`? Si un arreglo en general de Julia viene dado por
`Array{tipo, dim}`, ¿cómo piensas que Julia interpreta a un vector fila, i.e.,
es un vector o una matriz?

Para crear un vector columna a uno fila podemos utilizar `'`, p.g., `[1,2,3]' == [1 2 3]`.

#### Pregunta ####

¿Qué sucede cuando calculas la transpuesta de la transpuesta de un vector
**columna**? ¿Es lo que esperabas?

#### Pregunta ####

Para calcular el producto punto entre dos vectores puedes usar `a \cdot[TAB] b`, 
en donde `[TAB]` significa que tienes que presionar la tecla tabulación.
Utiliza la transpuesta de un vector para calcular el producto punto, ¿de qué
tipo es la salida?.

Para crear un vector con entradas aleatorias entre 0 y 1 se utiliza la orden `rand(dim)`.
Para crear un vector con entradas siguiente la distribución normal con desviación estándar 1 y media 0 `randn(dim)`.

#### Ejercicio ####

1. Instalen `Plots` usando `Pkg.add("Plots")`.
2. Utilizando `histogram(valores)` sustituyendo `valores` por un vector aleatorio siguiendo la distribución normal, generen un histograma.

#### Ejercicio ####
Crear una función que calcule un estado cuántico aleatorio que se llame `estadoaleatorio(dim)`, con m la dimensión que deseamos que tenga.

In [14]:
doc"""
Operación daga: daga([1im, 1im, 1im]) = -[1im 1im 1im]

Si `estadoaleatorio` devuelve $\vert \psi \rangle$, entonces, `daga` devuelve $\langle \psi \vert$.
"""
function daga(state::Array{Complex{Float64},2})
    return transpose(conj(state))
end

daga (generic function with 1 method)

In [15]:
?daga

search: daga Diagonal Bidiagonal Tridiagonal SymTridiagonal diagm diag diagind



Operación daga: daga([1im, 1im, 1im]) = -[1im 1im 1im]

Si `estadoaleatorio` devuelve $\vert \psi \rangle$, entonces, `daga` devuelve $\langle \psi \vert$.


####  Ejercicio ####

Utilizando la función `daga` programar:
+ Una función que calcule el producto punto entre dos estados cuánticos.
+ Una función que calcule el proyector de un estado cuántico.

## Matrices ##

Para crear la matriz identidad utilizas `eye(tipo, dim)`. Para crear una matriz
llenar de cero se utiliza la orden `zeros(tipo, dim)`. Para crear una matriz
aleatoria con entradas siguiente la distribución normal con media
0 y desviación estándar 1 se utiliza `randn(tipo, [dims])`.

#### Ejemplo ####

Diagonalizar una matriz.

In [1]:
mat = [1 2 3; 3 5. 3; 4 5 16]

3x3 Array{Float64,2}:
 1.0  2.0   3.0
 3.0  5.0   3.0
 4.0  5.0  16.0

In [4]:
vecs = eigvecs(mat)

3x3 Array{Float64,2}:
 -0.195173  -0.88552    -0.160238
 -0.259389   0.458214   -0.88965 
 -0.945846   0.0767726   0.427606

In [6]:
inv(vecs)*mat*vecs

3x3 Array{Float64,2}:
 18.1966        4.44089e-16  8.88178e-16
 -5.59969e-15  -0.294997     2.91434e-16
 -3.55271e-15   9.99201e-16  4.0984     

In [11]:
function chop(mat, tol = 1e-5)
    for i in eachindex(mat)
        if abs(mat[i]) < tol
            mat[i] = 0.
        end
    end
    mat
end

chop (generic function with 2 methods)

In [12]:
chop(inv(vecs)*mat*vecs)

3x3 Array{Float64,2}:
 18.1966   0.0       0.0   
  0.0     -0.294997  0.0   
  0.0      0.0       4.0984

####  Ejercicio ####

Documentar la función `chop`.

####  Ejercicio ####

Crear una matriz *hermitiana* y diagonalizarla. Utilizar `chop` si es necesario.

####  Ejercicio ####

Crear una matriz $H$ *hermitiana* y obtener $h$,la matriz $H$ diagoanlizada. Utilizar `chop` si es necesario. 
+ Utilizar la función `expm` para calcular $\exp(-i h)$ con $h$ la matriz que diagonalizaron. 
+ Calcular los eigenvalores de $\exp(-i h)$.
+ Calcular los eigenvalores de $\exp(-i H)$.

## Producto tensorial ##

Las matrices de Pauli son,

$$
\sigma_x = \begin{pmatrix}0&1\\1&0\end{pmatrix}, 
\sigma_y = \begin{pmatrix}0&-i\\i&0\end{pmatrix}, 
\sigma_z = \begin{pmatrix}1&0\\0&-1\end{pmatrix}
$$

In [16]:
function pauli(n=3)
    if n == 1
        return [0. 1; 1 0]
    elseif n == 2
        return [0 -1.im; 1im 0]
    elseif n == 3
        return [1. 0; 0 -1]
    else
        return eye(2)
    end
end

pauli (generic function with 2 methods)

Se entiende que $\sigma_z(2) = \mathbb{1}\otimes\sigma_z$.

Para calcular $\sigma_z(n)$ cuando tenemos un sistema formado por $k$ espines utilizaremos esta función.

In [18]:
function paulin(n, k)
    mat = fill(eye(2), k)
    mat[n] = pauli()
    kron(mat...)
end

paulin (generic function with 1 method)

In [23]:
norm(paulin(3, 3)-kron(eye(2),eye(2),pauli()))

0.0

##  Tarea

Todo lo siguiente tiene que subirse a Travis

1. Generar una matriz hermitiana de $n\times n$, calcular sus eigenvectors, calcular los proyectores de los eigenvectores y comprobar que la suma es la identidad de $n\times n$.
2. Crear una matriz *hermitiana* y diagonalizarla. Utilizar `chop` si es necesario. 
    + Utilizar la función `expm` para calcular $\exp(-i h)$ con $h$ la matriz que diagonalizaron. 
    + Calcular los eigenvalores de $\exp(-i h)$.
    + Calcular las fases de los eigenvalores que calcularon en el paso anterior.
    + Hacer un histograma de estas fases.